In [8]:
import polars as pl
from scipy.stats import norm, poisson
import numpy as np
import datetime
import tensorflow as tf
import plotly.graph_objects as go
from typing import Literal
from src.dataLoader import getResultDataframe

In [9]:
dfResult = getResultDataframe()
if dfResult is None:
    print("No data found. Please make sure the results.csv file is in the data/ directory.")
    dfResult = pl.DataFrame()

In [10]:
dfResult

shape: (49_477, 9)
┌────────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬─────────┐
│ date       ┆ home_team ┆ away_team ┆ home_scor ┆ … ┆ tournamen ┆ city      ┆ country   ┆ neutral │
│ ---        ┆ ---       ┆ ---       ┆ e         ┆   ┆ t         ┆ ---       ┆ ---       ┆ ---     │
│ str        ┆ str       ┆ str       ┆ ---       ┆   ┆ ---       ┆ str       ┆ str       ┆ bool    │
│            ┆           ┆           ┆ i64       ┆   ┆ str       ┆           ┆           ┆         │
╞════════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═════════╡
│ 1872-11-30 ┆ Scotland  ┆ England   ┆ 0         ┆ … ┆ Friendly  ┆ Glasgow   ┆ Scotland  ┆ false   │
│ 1873-03-08 ┆ England   ┆ Scotland  ┆ 4         ┆ … ┆ Friendly  ┆ London    ┆ England   ┆ false   │
│ 1874-03-07 ┆ Scotland  ┆ England   ┆ 2         ┆ … ┆ Friendly  ┆ Glasgow   ┆ Scotland  ┆ false   │
│ 1875-03-06 ┆ England   ┆ Scotland  ┆ 2         ┆ … ┆ Friendly  ┆ London    ┆ England   ┆ false   │
│ 1876-03-04 ┆ Scotland  ┆ England   ┆ 3         ┆ … ┆ Friendly  ┆ Glasgow   ┆ Scotland  ┆ false   │
│ …          ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …       │
│ 2026-06-27 ┆ Jordan    ┆ Argentina ┆ null      ┆ … ┆ FIFA      ┆ Arlington ┆ United    ┆ true    │
│            ┆           ┆           ┆           ┆   ┆ World Cup ┆           ┆ States    ┆         │
│ 2026-06-27 ┆ Colombia  ┆ Portugal  ┆ null      ┆ … ┆ FIFA      ┆ Miami     ┆ United    ┆ true    │
│            ┆           ┆           ┆           ┆   ┆ World Cup ┆ Gardens   ┆ States    ┆         │
│ 2026-06-27 ┆ DR Congo  ┆ Uzbekista ┆ null      ┆ … ┆ FIFA      ┆ Atlanta   ┆ United    ┆ true    │
│            ┆           ┆ n         ┆           ┆   ┆ World Cup ┆           ┆ States    ┆         │
│ 2026-06-27 ┆ Panama    ┆ England   ┆ null      ┆ … ┆ FIFA      ┆ East Ruth ┆ United    ┆ true    │
│            ┆           ┆           ┆           ┆   ┆ World Cup ┆ erford    ┆ States    ┆         │
│ 2026-06-27 ┆ Croatia   ┆ Ghana     ┆ null      ┆ … ┆ FIFA      ┆ Philadelp ┆ United    ┆ true    │
│            ┆           ┆           ┆           ┆   ┆ World Cup ┆ hia       ┆ States    ┆         │
└────────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴─────────┘

In [12]:
allTeams = dfResult["home_team"].unique().to_list() + dfResult["away_team"].unique().to_list()
allTeams = np.sort(list(set(allTeams)))
defendingParams = np.random.normal(1.5,0.4, len(allTeams))
attackingParams = np.random.normal(1.5,0.4, len(allTeams))
dfParams = pl.DataFrame({
    "team": allTeams,
    "num": range(len(allTeams)),
    "defending": defendingParams,
    "attacking": attackingParams
})
dictNum = {}
for i, team in enumerate(allTeams):
    dictNum[str(team)] = i
numTeams = len(allTeams)

In [13]:
def getMatchMatrice(
    dfMatch: pl.DataFrame, 
    scope: pl.Expr,
    teamNumerotation: dict[str, int]
    ) -> np.ndarray:
    numTeams = len(teamNumerotation)
    df = dfMatch.filter(scope)
    res = np.zeros((df.height*2, numTeams*2 + 3))
    for i, row in enumerate(df.iter_rows(named=True)):
        #home team score
        res[2*i, teamNumerotation[str(row["home_team"])]] = 1
        res[2*i, numTeams+teamNumerotation[str(row["away_team"])]] = 1
        res[2*i, -1] = row["home_score"]
        #away team score
        res[2*i + 1, numTeams+teamNumerotation[str(row["home_team"])]] = 1
        res[2*i + 1, teamNumerotation[str(row["away_team"])]] = 1
        res[2*i + 1, -1] = row["away_score"]

        if not row["neutral"]:
            res[2*i, -3] = 1
            res[2*i + 1, -2] = 1
    return res

In [16]:
scope = pl.lit(True)
scope = scope & (pl.col("date").is_between(datetime.date(2025, 6, 1), datetime.date(2026, 6, 1)))
scope = scope & (pl.all_horizontal([pl.col(column).is_not_null() for column in dfResult.columns]))

matchMatrice = getMatchMatrice(dfResult, scope, dictNum)
matchMatrice

array([[0., 0., 0., ..., 1., 0., 2.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       ...,
       [0., 1., 0., ..., 0., 1., 1.],
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 3.]], shape=(1976, 675))

In [17]:
class MyModel(tf.keras.Model):
    def __init__(
        self,
        numTeams: int
    ):
        super().__init__()
        self.numTeams = numTeams
        self.teamParams = self.add_weight(
            name="team_params",
            shape=(2 * numTeams, 1),
            initializer=tf.random_normal_initializer(),
            trainable=True
        )
        self.awayHomeMultiplier = self.add_weight(
            name="away_home_multiplier",
            shape=(1, 2),
            initializer=tf.random_normal_initializer(),
            trainable=True
        )


    def call(self, input):
        attackingParams = self.teamParams[:self.numTeams]
        defendingParams = self.teamParams[self.numTeams:2*self.numTeams]

        attackingOneHotEncoder = input[:,:self.numTeams]
        defendingOneHotEncoder = input[:,self.numTeams:2*self.numTeams]
        score = input[:,-1]
        awayHomeMultiplier = tf.reduce_sum(input[:, -3:-1] * self.awayHomeMultiplier, axis=1, keepdims=True)
        scoreExpanded = tf.expand_dims(score, axis=1)

        params = tf.exp(awayHomeMultiplier + tf.matmul(attackingOneHotEncoder, attackingParams) - tf.matmul(defendingOneHotEncoder, defendingParams))
        
        poissonLogLikelyHood = -params + tf.math.log(params) * scoreExpanded - tf.math.lgamma(scoreExpanded + 1)

        return tf.reduce_sum(poissonLogLikelyHood)

In [18]:
X = tf.constant(matchMatrice, dtype=tf.float32)
model = MyModel(numTeams=numTeams)

In [19]:

model = MyModel(numTeams=numTeams)
optimizer = tf.keras.optimizers.Adam()
X = tf.constant(matchMatrice, dtype=tf.float32)
numEpoch = 10000
lossHistory = []
for i in range(numEpoch):
    print(f"Epoch {i+1}/{numEpoch}", end="\r")
    with tf.GradientTape() as tape:
        pred = -model(X)
        loss = pred
    lossHistory.append(loss)
    grads = tape.gradient(loss, model.trainable_variables)
    optimizer.apply_gradients(zip(grads, model.trainable_variables))

In [20]:
fig = go.Figure()
fig.add_trace(go.Scatter(y=lossHistory, mode='lines', name='Loss'))
fig.update_layout(title='Loss History', xaxis_title='Epoch', yaxis_title='Loss')
fig.show()

In [21]:
attack = [np.exp(model.teamParams.numpy())[i][0] for i in range(numTeams)]
defend = [np.exp(model.teamParams.numpy())[numTeams+i][0] for i in range(numTeams)]

In [22]:
dictAttack = {str(allTeams[i]): attack[i] for i in range(numTeams)}
dictDefend = {str(allTeams[i]): defend[i] for i in range(numTeams)}
dictAwayHome = {"home": np.exp(model.awayHomeMultiplier.numpy())[0][0], "away": np.exp(model.awayHomeMultiplier.numpy())[0][1]}

In [23]:

def getStatsDf(
    teamA: str, 
    teamB: str, 
    maxScore: int, 
    teamHome : Literal["first", "second", "neutral"]
    ) -> pl.DataFrame:
    dfDict = {
        teamA: [],
        teamB: [],
        "probability": []
    }
    multiplierA, multiplierB = 1, 1
    if teamHome == "first":
        multiplierA = dictAwayHome["home"]
        multiplierB = dictAwayHome["away"]
    elif teamHome == "second":
        multiplierA = dictAwayHome["away"]
        multiplierB = dictAwayHome["home"]

    for i in range(maxScore + 1):
        for j in range(maxScore + 1):
            dfDict[teamA].append(i)
            dfDict[teamB].append(j)
            prob = 100*poisson.pmf(i, multiplierA * dictAttack[teamA] / dictDefend[teamB]) * poisson.pmf(j, multiplierB * dictAttack[teamB] / dictDefend[teamA])
            dfDict["probability"].append(prob)
    res= pl.DataFrame(dfDict).sort("probability", descending=True)
    teamAWins = pl.col(teamA) > pl.col(teamB)
    teamBWins = pl.col(teamB) > pl.col(teamA)
    res = res.with_columns(
        result=pl.when(teamAWins).then(pl.lit(teamA)).when(teamBWins).then(pl.lit(teamB)).otherwise(pl.lit("draw")).alias("result")
    )
    resSummedUp = res.group_by("result").agg(pl.col("probability").sum())
    res = res.join(resSummedUp, on="result", how="left").rename({"probability_right": "result_probability"})
    res = res.with_columns(
        expectedGain = (3*pl.col("probability") + pl.col("result_probability") - pl.col("probability"))/100)
    return res

In [38]:
teamA = "Mexico"
teamB = "South Africa"
probScore = getStatsDf(teamA, teamB, 10, "first")
probScore = probScore.sort("expectedGain", descending=True)
probScore

shape: (121, 6)
┌────────┬──────────────┬─────────────┬──────────────┬────────────────────┬──────────────┐
│ Mexico ┆ South Africa ┆ probability ┆ result       ┆ result_probability ┆ expectedGain │
│ ---    ┆ ---          ┆ ---         ┆ ---          ┆ ---                ┆ ---          │
│ i64    ┆ i64          ┆ f64         ┆ str          ┆ f64                ┆ f64          │
╞════════╪══════════════╪═════════════╪══════════════╪════════════════════╪══════════════╡
│ 1      ┆ 0            ┆ 21.128443   ┆ Mexico       ┆ 68.065755          ┆ 1.103226     │
│ 2      ┆ 0            ┆ 17.308228   ┆ Mexico       ┆ 68.065755          ┆ 1.026822     │
│ 3      ┆ 0            ┆ 9.452495    ┆ Mexico       ┆ 68.065755          ┆ 0.869707     │
│ 2      ┆ 1            ┆ 7.09425     ┆ Mexico       ┆ 68.065755          ┆ 0.822543     │
│ 3      ┆ 1            ┆ 3.874363    ┆ Mexico       ┆ 68.065755          ┆ 0.758145     │
│ …      ┆ …            ┆ …           ┆ …            ┆ …                  ┆ …            │
│ 8      ┆ 9            ┆ 1.4941e-11  ┆ South Africa ┆ 8.811079           ┆ 0.088111     │
│ 6      ┆ 10           ┆ 1.2776e-11  ┆ South Africa ┆ 8.811079           ┆ 0.088111     │
│ 7      ┆ 10           ┆ 2.9902e-12  ┆ South Africa ┆ 8.811079           ┆ 0.088111     │
│ 8      ┆ 10           ┆ 6.1239e-13  ┆ South Africa ┆ 8.811079           ┆ 0.088111     │
│ 9      ┆ 10           ┆ 1.1148e-13  ┆ South Africa ┆ 8.811079           ┆ 0.088111     │
└────────┴──────────────┴─────────────┴──────────────┴────────────────────┴──────────────┘

In [39]:
teamA = "South Korea"
teamB = "Czech Republic"
probScore = getStatsDf(teamA, teamB, 10, "neutral")
probScore = probScore.sort("expectedGain", descending=True)
probScore

shape: (121, 6)
┌─────────────┬────────────────┬─────────────┬────────────────┬────────────────────┬──────────────┐
│ South Korea ┆ Czech Republic ┆ probability ┆ result         ┆ result_probability ┆ expectedGain │
│ ---         ┆ ---            ┆ ---         ┆ ---            ┆ ---                ┆ ---          │
│ i64         ┆ i64            ┆ f64         ┆ str            ┆ f64                ┆ f64          │
╞═════════════╪════════════════╪═════════════╪════════════════╪════════════════════╪══════════════╡
│ 2           ┆ 1              ┆ 9.789861    ┆ South Korea    ┆ 65.949242          ┆ 0.85529      │
│ 2           ┆ 0              ┆ 9.77232     ┆ South Korea    ┆ 65.949242          ┆ 0.854939     │
│ 1           ┆ 0              ┆ 8.602547    ┆ South Korea    ┆ 65.949242          ┆ 0.831543     │
│ 3           ┆ 1              ┆ 7.414056    ┆ South Korea    ┆ 65.949242          ┆ 0.807774     │
│ 3           ┆ 0              ┆ 7.400773    ┆ South Korea    ┆ 65.949242          ┆ 0.807508     │
│ …           ┆ …              ┆ …           ┆ …              ┆ …                  ┆ …            │
│ 6           ┆ 10             ┆ 2.0292e-7   ┆ Czech Republic ┆ 15.306362          ┆ 0.153064     │
│ 8           ┆ 9              ┆ 1.8671e-7   ┆ Czech Republic ┆ 15.306362          ┆ 0.153064     │
│ 7           ┆ 10             ┆ 6.5861e-8   ┆ Czech Republic ┆ 15.306362          ┆ 0.153064     │
│ 8           ┆ 10             ┆ 1.8704e-8   ┆ Czech Republic ┆ 15.306362          ┆ 0.153064     │
│ 9           ┆ 10             ┆ 4.7217e-9   ┆ Czech Republic ┆ 15.306362          ┆ 0.153064     │
└─────────────┴────────────────┴─────────────┴────────────────┴────────────────────┴──────────────┘

In [41]:
teamA = "Canada"
teamB = "Bosnia and Herzegovina"
probScore = getStatsDf(teamA, teamB, 10, "first")
probScore = probScore.sort("expectedGain", descending=True)
probScore

shape: (121, 6)
┌────────┬─────────────┬─────────────┬─────────────┬────────────────────┬──────────────┐
│ Canada ┆ Bosnia and  ┆ probability ┆ result      ┆ result_probability ┆ expectedGain │
│ ---    ┆ Herzegovina ┆ ---         ┆ ---         ┆ ---                ┆ ---          │
│ i64    ┆ ---         ┆ f64         ┆ str         ┆ f64                ┆ f64          │
│        ┆ i64         ┆             ┆             ┆                    ┆              │
╞════════╪═════════════╪═════════════╪═════════════╪════════════════════╪══════════════╡
│ 1      ┆ 0           ┆ 21.5127     ┆ Canada      ┆ 69.840171          ┆ 1.128656     │
│ 2      ┆ 0           ┆ 18.015692   ┆ Canada      ┆ 69.840171          ┆ 1.058716     │
│ 3      ┆ 0           ┆ 10.058095   ┆ Canada      ┆ 69.840171          ┆ 0.899564     │
│ 2      ┆ 1           ┆ 6.798845    ┆ Canada      ┆ 69.840171          ┆ 0.834379     │
│ 4      ┆ 0           ┆ 4.211548    ┆ Canada      ┆ 69.840171          ┆ 0.782633     │
│ …      ┆ …           ┆ …           ┆ …           ┆ …                  ┆ …            │
│ 8      ┆ 9           ┆ 8.4406e-12  ┆ Bosnia and  ┆ 7.820214           ┆ 0.078202     │
│        ┆             ┆             ┆ Herzegovina ┆                    ┆              │
│ 6      ┆ 10          ┆ 6.3587e-12  ┆ Bosnia and  ┆ 7.820214           ┆ 0.078202     │
│        ┆             ┆             ┆ Herzegovina ┆                    ┆              │
│ 7      ┆ 10          ┆ 1.5215e-12  ┆ Bosnia and  ┆ 7.820214           ┆ 0.078202     │
│        ┆             ┆             ┆ Herzegovina ┆                    ┆              │
│ 8      ┆ 10          ┆ 3.1853e-13  ┆ Bosnia and  ┆ 7.820214           ┆ 0.078202     │
│        ┆             ┆             ┆ Herzegovina ┆                    ┆              │
│ 9      ┆ 10          ┆ 5.9279e-14  ┆ Bosnia and  ┆ 7.820214           ┆ 0.078202     │
│        ┆             ┆             ┆ Herzegovina ┆                    ┆              │
└────────┴─────────────┴─────────────┴─────────────┴────────────────────┴──────────────┘

In [47]:
teamA = "United States"
teamB = "Paraguay"
probScore = getStatsDf(teamA, teamB, 10, "first")
probScore = probScore.sort("expectedGain", descending=True)
probScore

shape: (121, 6)
┌───────────────┬──────────┬─────────────┬──────────┬────────────────────┬──────────────┐
│ United States ┆ Paraguay ┆ probability ┆ result   ┆ result_probability ┆ expectedGain │
│ ---           ┆ ---      ┆ ---         ┆ ---      ┆ ---                ┆ ---          │
│ i64           ┆ i64      ┆ f64         ┆ str      ┆ f64                ┆ f64          │
╞═══════════════╪══════════╪═════════════╪══════════╪════════════════════╪══════════════╡
│ 0             ┆ 1        ┆ 9.810563    ┆ Paraguay ┆ 50.592211          ┆ 0.702133     │
│ 1             ┆ 2        ┆ 9.63601     ┆ Paraguay ┆ 50.592211          ┆ 0.698642     │
│ 0             ┆ 2        ┆ 8.399115    ┆ Paraguay ┆ 50.592211          ┆ 0.673904     │
│ 1             ┆ 3        ┆ 5.499784    ┆ Paraguay ┆ 50.592211          ┆ 0.615918     │
│ 0             ┆ 3        ┆ 4.793822    ┆ Paraguay ┆ 50.592211          ┆ 0.601799     │
│ …             ┆ …        ┆ …           ┆ …        ┆ …                  ┆ …            │
│ 6             ┆ 6        ┆ 0.000635    ┆ draw     ┆ 23.879353          ┆ 0.238806     │
│ 7             ┆ 7        ┆ 0.000025    ┆ draw     ┆ 23.879353          ┆ 0.238794     │
│ 8             ┆ 8        ┆ 7.8154e-7   ┆ draw     ┆ 23.879353          ┆ 0.238794     │
│ 9             ┆ 9        ┆ 1.8954e-8   ┆ draw     ┆ 23.879353          ┆ 0.238794     │
│ 10            ┆ 10       ┆ 3.7233e-10  ┆ draw     ┆ 23.879353          ┆ 0.238794     │
└───────────────┴──────────┴─────────────┴──────────┴────────────────────┴──────────────┘

In [43]:
teamA = "Switzerland"
teamB = "Qatar"
probScore = getStatsDf(teamA, teamB, 10, "neutral")
probScore = probScore.sort("expectedGain", descending=True)
probScore

shape: (121, 6)
┌─────────────┬───────┬─────────────┬─────────────┬────────────────────┬──────────────┐
│ Switzerland ┆ Qatar ┆ probability ┆ result      ┆ result_probability ┆ expectedGain │
│ ---         ┆ ---   ┆ ---         ┆ ---         ┆ ---                ┆ ---          │
│ i64         ┆ i64   ┆ f64         ┆ str         ┆ f64                ┆ f64          │
╞═════════════╪═══════╪═════════════╪═════════════╪════════════════════╪══════════════╡
│ 7           ┆ 0     ┆ 10.226488   ┆ Switzerland ┆ 89.051183          ┆ 1.095042     │
│ 6           ┆ 0     ┆ 10.092132   ┆ Switzerland ┆ 89.051183          ┆ 1.092354     │
│ 8           ┆ 0     ┆ 9.067305    ┆ Switzerland ┆ 89.051183          ┆ 1.071858     │
│ 5           ┆ 0     ┆ 8.536749    ┆ Switzerland ┆ 89.051183          ┆ 1.061247     │
│ 9           ┆ 0     ┆ 7.146236    ┆ Switzerland ┆ 89.051183          ┆ 1.033437     │
│ …           ┆ …     ┆ …           ┆ …           ┆ …                  ┆ …            │
│ 3           ┆ 10    ┆ 5.2512e-11  ┆ Qatar       ┆ 0.076003           ┆ 0.00076      │
│ 0           ┆ 9     ┆ 2.3493e-11  ┆ Qatar       ┆ 0.076003           ┆ 0.00076      │
│ 2           ┆ 10    ┆ 2.2209e-11  ┆ Qatar       ┆ 0.076003           ┆ 0.00076      │
│ 1           ┆ 10    ┆ 6.2622e-12  ┆ Qatar       ┆ 0.076003           ┆ 0.00076      │
│ 0           ┆ 10    ┆ 8.8284e-13  ┆ Qatar       ┆ 0.076003           ┆ 0.00076      │
└─────────────┴───────┴─────────────┴─────────────┴────────────────────┴──────────────┘

In [44]:
teamA = "Brazil"
teamB = "Morocco"
probScore = getStatsDf(teamA, teamB, 10, "neutral")
probScore = probScore.sort("expectedGain", descending=True)
probScore

shape: (121, 6)
┌────────┬─────────┬─────────────┬─────────┬────────────────────┬──────────────┐
│ Brazil ┆ Morocco ┆ probability ┆ result  ┆ result_probability ┆ expectedGain │
│ ---    ┆ ---     ┆ ---         ┆ ---     ┆ ---                ┆ ---          │
│ i64    ┆ i64     ┆ f64         ┆ str     ┆ f64                ┆ f64          │
╞════════╪═════════╪═════════════╪═════════╪════════════════════╪══════════════╡
│ 0      ┆ 0       ┆ 18.002418   ┆ draw    ┆ 33.849288          ┆ 0.698541     │
│ 1      ┆ 0       ┆ 15.994216   ┆ Brazil  ┆ 34.808766          ┆ 0.667972     │
│ 0      ┆ 1       ┆ 14.873884   ┆ Morocco ┆ 31.341945          ┆ 0.610897     │
│ 1      ┆ 1       ┆ 13.214676   ┆ draw    ┆ 33.849288          ┆ 0.602786     │
│ 2      ┆ 0       ┆ 7.105016    ┆ Brazil  ┆ 34.808766          ┆ 0.490188     │
│ …      ┆ …       ┆ …           ┆ …       ┆ …                  ┆ …            │
│ 6      ┆ 10      ┆ 5.0230e-10  ┆ Morocco ┆ 31.341945          ┆ 0.313419     │
│ 8      ┆ 9       ┆ 8.5693e-11  ┆ Morocco ┆ 31.341945          ┆ 0.313419     │
│ 7      ┆ 10      ┆ 6.3753e-11  ┆ Morocco ┆ 31.341945          ┆ 0.313419     │
│ 8      ┆ 10      ┆ 7.0801e-12  ┆ Morocco ┆ 31.341945          ┆ 0.313419     │
│ 9      ┆ 10      ┆ 6.9892e-13  ┆ Morocco ┆ 31.341945          ┆ 0.313419     │
└────────┴─────────┴─────────────┴─────────┴────────────────────┴──────────────┘

In [45]:
teamA = "Haiti"
teamB = "Scotland"
probScore = getStatsDf(teamA, teamB, 10, "neutral")
probScore = probScore.sort("expectedGain", descending=True)
probScore

shape: (121, 6)
┌───────┬──────────┬─────────────┬──────────┬────────────────────┬──────────────┐
│ Haiti ┆ Scotland ┆ probability ┆ result   ┆ result_probability ┆ expectedGain │
│ ---   ┆ ---      ┆ ---         ┆ ---      ┆ ---                ┆ ---          │
│ i64   ┆ i64      ┆ f64         ┆ str      ┆ f64                ┆ f64          │
╞═══════╪══════════╪═════════════╪══════════╪════════════════════╪══════════════╡
│ 0     ┆ 2        ┆ 12.062313   ┆ Scotland ┆ 73.494158          ┆ 0.976188     │
│ 0     ┆ 1        ┆ 10.040976   ┆ Scotland ┆ 73.494158          ┆ 0.935761     │
│ 0     ┆ 3        ┆ 9.660376    ┆ Scotland ┆ 73.494158          ┆ 0.928149     │
│ 1     ┆ 2        ┆ 9.317377    ┆ Scotland ┆ 73.494158          ┆ 0.921289     │
│ 1     ┆ 3        ┆ 7.462032    ┆ Scotland ┆ 73.494158          ┆ 0.884182     │
│ …     ┆ …        ┆ …           ┆ …        ┆ …                  ┆ …            │
│ 9     ┆ 8        ┆ 3.1049e-8   ┆ Haiti    ┆ 10.132898          ┆ 0.101329     │
│ 10    ┆ 6        ┆ 2.3267e-8   ┆ Haiti    ┆ 10.132898          ┆ 0.101329     │
│ 10    ┆ 7        ┆ 7.9859e-9   ┆ Haiti    ┆ 10.132898          ┆ 0.101329     │
│ 10    ┆ 8        ┆ 2.3984e-9   ┆ Haiti    ┆ 10.132898          ┆ 0.101329     │
│ 10    ┆ 9        ┆ 6.4026e-10  ┆ Haiti    ┆ 10.132898          ┆ 0.101329     │
└───────┴──────────┴─────────────┴──────────┴────────────────────┴──────────────┘

In [46]:
teamA = "Australia"
teamB = "Turkey"
probScore = getStatsDf(teamA, teamB, 10, "neutral")
probScore = probScore.sort("expectedGain", descending=True)
probScore

shape: (121, 6)
┌───────────┬────────┬─────────────┬───────────┬────────────────────┬──────────────┐
│ Australia ┆ Turkey ┆ probability ┆ result    ┆ result_probability ┆ expectedGain │
│ ---       ┆ ---    ┆ ---         ┆ ---       ┆ ---                ┆ ---          │
│ i64       ┆ i64    ┆ f64         ┆ str       ┆ f64                ┆ f64          │
╞═══════════╪════════╪═════════════╪═══════════╪════════════════════╪══════════════╡
│ 2         ┆ 1      ┆ 8.793747    ┆ Australia ┆ 40.999542          ┆ 0.58587      │
│ 1         ┆ 0      ┆ 8.161701    ┆ Australia ┆ 40.999542          ┆ 0.573229     │
│ 2         ┆ 0      ┆ 6.29754     ┆ Australia ┆ 40.999542          ┆ 0.535946     │
│ 1         ┆ 2      ┆ 7.957137    ┆ Turkey    ┆ 34.488844          ┆ 0.504031     │
│ 3         ┆ 1      ┆ 4.523483    ┆ Australia ┆ 40.999542          ┆ 0.500465     │
│ …         ┆ …      ┆ …           ┆ …         ┆ …                  ┆ …            │
│ 6         ┆ 6      ┆ 0.001021    ┆ draw      ┆ 24.511514          ┆ 0.245136     │
│ 7         ┆ 7      ┆ 0.000045    ┆ draw      ┆ 24.511514          ┆ 0.245116     │
│ 8         ┆ 8      ┆ 0.000002    ┆ draw      ┆ 24.511514          ┆ 0.245115     │
│ 9         ┆ 9      ┆ 4.0239e-8   ┆ draw      ┆ 24.511514          ┆ 0.245115     │
│ 10        ┆ 10     ┆ 8.6710e-10  ┆ draw      ┆ 24.511514          ┆ 0.245115     │
└───────────┴────────┴─────────────┴───────────┴────────────────────┴──────────────┘

In [51]:
teamA = "Netherlands"
teamB = "Japan"
probScore = getStatsDf(teamA, teamB, 10, "neutral")
probScore = probScore.sort("expectedGain", descending=True)
probScore

shape: (121, 6)
┌─────────────┬───────┬─────────────┬─────────────┬────────────────────┬──────────────┐
│ Netherlands ┆ Japan ┆ probability ┆ result      ┆ result_probability ┆ expectedGain │
│ ---         ┆ ---   ┆ ---         ┆ ---         ┆ ---                ┆ ---          │
│ i64         ┆ i64   ┆ f64         ┆ str         ┆ f64                ┆ f64          │
╞═════════════╪═══════╪═════════════╪═════════════╪════════════════════╪══════════════╡
│ 1           ┆ 0     ┆ 10.533545   ┆ Netherlands ┆ 37.399001          ┆ 0.584661     │
│ 0           ┆ 1     ┆ 10.200548   ┆ Japan       ┆ 35.49291           ┆ 0.55894      │
│ 2           ┆ 1     ┆ 8.114149    ┆ Netherlands ┆ 37.399001          ┆ 0.536273     │
│ 1           ┆ 1     ┆ 12.866139   ┆ draw        ┆ 27.108072          ┆ 0.528404     │
│ 1           ┆ 2     ┆ 7.857637    ┆ Japan       ┆ 35.49291           ┆ 0.512082     │
│ …           ┆ …     ┆ …           ┆ …           ┆ …                  ┆ …            │
│ 6           ┆ 6     ┆ 0.000215    ┆ draw        ┆ 27.108072          ┆ 0.271085     │
│ 7           ┆ 7     ┆ 0.000007    ┆ draw        ┆ 27.108072          ┆ 0.271081     │
│ 8           ┆ 8     ┆ 1.6304e-7   ┆ draw        ┆ 27.108072          ┆ 0.271081     │
│ 9           ┆ 9     ┆ 3.1011e-9   ┆ draw        ┆ 27.108072          ┆ 0.271081     │
│ 10          ┆ 10    ┆ 4.7776e-11  ┆ draw        ┆ 27.108072          ┆ 0.271081     │
└─────────────┴───────┴─────────────┴─────────────┴────────────────────┴──────────────┘

In [29]:
teamAWins = probScore.filter(pl.col(teamA) > pl.col(teamB)).select(pl.col("probability").sum())[0,0]
teamBWins = probScore.filter(pl.col(teamB) > pl.col(teamA)).select(pl.col("probability").sum())[0,0]
draws = probScore.filter(pl.col(teamA) == pl.col(teamB)).select(pl.col("probability").sum())[0,0]
print(f"{teamA} wins: {teamAWins:.2f}%")
print(f"{teamB} wins: {teamBWins:.2f}%")
print(f"Draw: {draws:.2f}%")

Switzerland wins: 89.05%
Qatar wins: 0.08%
Draw: 0.35%

In [30]:
teamBWins

0.07600326636251822

In [31]:
dictAttack["South Africa"]

np.float32(1.7621456)

In [32]:
dictDefend["Mexico"]

np.float32(3.2489254)

In [33]:
dictDefend["South Africa"]

np.float32(1.4767506)

In [34]:
df = pl.DataFrame({
    "team": allTeams,
    "attack": attack,
    "defend": defend
})

In [35]:
df

shape: (336, 3)
┌───────────────┬──────────┬──────────┐
│ team          ┆ attack   ┆ defend   │
│ ---           ┆ ---      ┆ ---      │
│ str           ┆ f32      ┆ f32      │
╞═══════════════╪══════════╪══════════╡
│ Abkhazia      ┆ 1.044979 ┆ 0.923829 │
│ Afghanistan   ┆ 0.279899 ┆ 1.882492 │
│ Albania       ┆ 1.202819 ┆ 1.914672 │
│ Alderney      ┆ 0.92874  ┆ 0.987386 │
│ Algeria       ┆ 2.860874 ┆ 2.432289 │
│ …             ┆ …        ┆ …        │
│ Yugoslavia    ┆ 1.025531 ┆ 0.998298 │
│ Zambia        ┆ 1.070424 ┆ 0.930199 │
│ Zanzibar      ┆ 1.058106 ┆ 0.979473 │
│ Zimbabwe      ┆ 1.104917 ┆ 1.211552 │
│ Åland Islands ┆ 0.971696 ┆ 0.99184  │
└───────────────┴──────────┴──────────┘

In [36]:
defend

[np.float32(0.92382944),
 np.float32(1.8824924),
 np.float32(1.9146717),
 np.float32(0.98738605),
 np.float32(2.4322894),
 np.float32(1.0553608),
 np.float32(0.014829345),
 np.float32(1.0611525),
 np.float32(0.86217606),
 np.float32(1.0563145),
 np.float32(0.14371249),
 np.float32(0.4014761),
 np.float32(1.0604836),
 np.float32(5.865772),
 np.float32(0.77195626),
 np.float32(1.0829071),
 np.float32(0.36109927),
 np.float32(1.0166723),
 np.float32(2.6651092),
 np.float32(3.339317),
 np.float32(0.9839398),
 np.float32(1.2733492),
 np.float32(0.13357161),
 np.float32(0.8122601),
 np.float32(0.31903607),
 np.float32(0.9522815),
 np.float32(0.24384576),
 np.float32(137.15512),
 np.float32(1.2105213),
 np.float32(1.44918),
 np.float32(0.43527353),
 np.float32(1.4818473),
 np.float32(0.35042086),
 np.float32(0.20936248),
 np.float32(1.0475881),
 np.float32(1.8704505),
 np.float32(0.28080064),
 np.float32(1.6307778),
 np.float32(0.8832452),
 np.float32(3.1684725),
 np.float32(0.2835322),
 np.float32(1.0497967),
 np.float32(0.22479287),
 np.float32(0.9163609),
 np.float32(1.5188717),
 np.float32(1.0057837),
 np.float32(0.60590667),
 np.float32(2.6427739),
 np.float32(4.356878),
 np.float32(0.9949496),
 np.float32(1.6940145),
 np.float32(1.026419),
 np.float32(0.96327853),
 np.float32(0.33143565),
 np.float32(0.5212431),
 np.float32(0.97392964),
 np.float32(0.6982662),
 np.float32(1.036177),
 np.float32(1.0684649),
 np.float32(1.034345),
 np.float32(1.5061563),
 np.float32(1.3126726),
 np.float32(1.011852),
 np.float32(2.5277922),
 np.float32(0.9913936),
 np.float32(1.0332885),
 np.float32(0.9963095),
 np.float32(1.0918812),
 np.float32(1.0986121),
 np.float32(1.0840982),
 np.float32(0.984731),
 np.float32(2.4028854),
 np.float32(0.3468507),
 np.float32(1.0512911),
 np.float32(0.8224381),
 np.float32(1.4268824),
 np.float32(0.94303095),
 np.float32(3.0014935),
 np.float32(1.0491768),
 np.float32(1.854506),
 np.float32(0.47291583),
 np.float32(0.3279611),
 np.float32(0.89516497),
 np.float32(0.9945532),
 np.float32(0.94506794),
 np.float32(0.413847),
 np.float32(6.192023),
 np.float32(2.9962916),
 np.float32(0.97046286),
 np.float32(1.0291435),
 np.float32(1.000253),
 np.float32(2.8497372),
 np.float32(0.9895131),
 np.float32(0.9859766),
 np.float32(0.9123543),
 np.float32(0.7007911),
 np.float32(0.80563533),
 np.float32(1.0902148),
 np.float32(1.5507176),
 np.float32(0.9569737),
 np.float32(0.1383955),
 np.float32(1.6356366),
 np.float32(3.1270742),
 np.float32(0.9835264),
 np.float32(0.9766605),
 np.float32(0.24127406),
 np.float32(0.74141717),
 np.float32(0.9601847),
 np.float32(0.95208776),
 np.float32(1.325296),
 np.float32(0.98454523),
 np.float32(2.0836604),
 np.float32(1.6340976),
 np.float32(0.5639331),
 np.float32(1.012387),
 np.float32(1.0595825),
 np.float32(1.7390972),
 np.float32(1.044828),
 np.float32(0.41891885),
 np.float32(0.45755178),
 np.float32(0.20630497),
 np.float32(0.90405315),
 np.float32(1.0399492),
 np.float32(1.526941),
 np.float32(0.86266744),
 np.float32(0.82251436),
 np.float32(0.9519618),
 np.float32(1.2395782),
 np.float32(0.33409074),
 np.float32(0.9679158),
 np.float32(1.3759904),
 np.float32(0.4041371),
 np.float32(1.6861564),
 np.float32(1.5573184),
 np.float32(0.5858655),
 np.float32(0.88767576),
 np.float32(2.8378413),
 np.float32(2.2397156),
 np.float32(1.0359505),
 np.float32(0.47409075),
 np.float32(1.0413799),
 np.float32(1.0905598),
 np.float32(1.5067203),
 np.float32(3.2159975),
 np.float32(1.5952345),
 np.float32(3.8154638),
 np.float32(0.69358104),
 np.float32(1.346),
 np.float32(0.9671888),
 np.float32(1.0645559),
 np.float32(0.7129385),
 np.float32(0.9569248),
 np.float32(1.0563254),
 np.float32(1.9242791),
 np.float32(1.059875),
 np.float32(0.8222002),
 np.float32(0.5549762),
 np.float32(0.9821286),
 np.float32(0.25264174),
 np.float32(0.77703965),
 np.float32(1.2060573),
 np.float32(0.90172946),
 np.float32(0.713673),
 np.float32(1.9805768),
 np.float32(0.5300116),
 np.float32(1.2893729),
 np.float32(1.0109767),
 np.float32(1.2369356),
 np.float32(0.14798766),
 np.float32(0.7836131),
 np.float32(0.9856619),
 np.float32(0.921248),
 np.float32(1.1164811),
 np.float32(0.37432027),
 np.float32(2.6814198),
 np.float32(0.7856078),
 np.float32(1.0520604),
 np.float32(0.9636554),
 np.float32(0.022191074),
 np.float32(0.52849734),
 np.float32(1.0043601),
 np.float32(1.0103295),
 np.float32(1.3399287),
 np.float32(0.83577216),
 np.float32(1.099284),
 np.float32(1.0238962),
 np.float32(3.2489254),
 np.float32(1.0078938),
 np.float32(0.6788312),
 np.float32(0.9477559),
 np.float32(0.25092098),
 np.float32(0.6899161),
 np.float32(0.679596),
 np.float32(5.8928103),
 np.float32(0.91633487),
 np.float32(0.55137914),
 np.float32(0.67013735),
 np.float32(0.58575225),
 np.float32(2.8006725),
 np.float32(1.4067454),
 np.float32(1.907413),
 np.float32(0.82086766),
 np.float32(0.9942405),
 np.float32(2.60532),
 np.float32(0.9946602),
 np.float32(0.6682096),
 np.float32(1.4336601),
 np.float32(0.9691459),
 np.float32(1.102457),
 np.float32(2.3273363),
 np.float32(0.988161),
 np.float32(3.6302187),
 np.float32(0.9712928),
 np.float32(1.3331053),
 np.float32(0.48253828),
 np.float32(1.0668899),
 np.float32(0.3858763),
 np.float32(1.0122135),
 np.float32(2.1227446),
 np.float32(1.458933),
 np.float32(1.0510919),
 np.float32(0.28509423),
 np.float32(2.8236718),
 np.float32(0.9483231),
 np.float32(1.9516196),
 np.float32(0.4847099),
 np.float32(1.8513432),
 np.float32(2.5542932),
 np.float32(0.8939106),
 np.float32(0.70541054),
 np.float32(0.78296584),
 np.float32(1.009679),
 np.float32(0.96147835),
 np.float32(2.3016188),
 np.float32(1.0224692),
 np.float32(0.97132397),
 np.float32(0.93557173),
 np.float32(1.2904702),
 np.float32(1.9657542),
 np.float32(1.6113591),
 np.float32(1.01141),
 np.float32(0.91848433),
 np.float32(0.9686755),
 np.float32(1.0723075),
 np.float32(0.9223426),
 np.float32(0.9829372),
 np.float32(0.20079087),
 np.float32(0.2738391),
 np.float32(0.4466347),
 np.float32(0.9902046),
 np.float32(0.40239057),
 np.float32(0.9479172),
 np.float32(0.44814232),
 np.float32(0.89859354),
 np.float32(1.3520392),
 np.float32(0.9989806),
 np.float32(1.9906645),
 np.float32(0.9555459),
 np.float32(1.0379939),
 np.float32(2.0771708),
 np.float32(1.0956651),
 np.float32(0.31881228),
 np.float32(0.43535924),
 np.float32(1.2617525),
 np.float32(0.9912203),
 np.float32(0.36138892),
 np.float32(0.74913853),
 np.float32(1.2320975),
 np.float32(2.3412354),
 np.float32(0.16273914),
 np.float32(0.99255943),
 np.float32(1.054733),
 np.float32(1.4767506),
 np.float32(1.9200002),
 np.float32(0.95997465),
 np.float32(0.69543636),
 np.float32(0.9223234),
 np.float32(3.0897424),
 np.float32(0.15725666),
 np.float32(1.220202),
 np.float32(0.9920736),
 np.float32(1.0734242),
 np.float32(1.5599431),
 np.float32(3.4514472),
 np.float32(1.7351011),
 np.float32(1.0186151),
 np.float32(0.98066574),
 np.float32(0.37330574),
 np.float32(1.0168564),
 np.float32(0.124972254),
 np.float32(0.9096078),
 np.float32(6.525124),
 np.float32(1.3212446),
 np.float32(0.3913821),
 np.float32(0.3982065),
 np.float32(0.97497886),
 np.float32(0.32690802),
 np.float32(1.2668817),
 np.float32(1.0218374),
 np.float32(0.8010139),
 np.float32(2.1652296),
 np.float32(1.8359492),
 np.float32(0.271176),
 np.float32(0.053067725),
 np.float32(1.020034),
 np.float32(1.0354857),
 np.float32(1.0229312),
 np.float32(1.7489316),
 np.float32(1.3399184),
 np.float32(1.0491694),
 np.float32(1.35649),
 np.float32(0.19774301),
 np.float32(2.6375382),
 np.float32(2.5345647),
 np.float32(0.21965694),
 np.float32(1.0351223),
 np.float32(1.4588071),
 np.float32(0.50372636),
 np.float32(1.0213354),
 np.float32(1.1813616),
 np.float32(1.0113729),
 np.float32(0.8945242),
 np.float32(1.1124454),
 np.float32(0.99730575),
 np.float32(0.08224471),
 np.float32(0.9321074),
 np.float32(0.44873092),
 np.float32(1.0781516),
 np.float32(221.06337),
 np.float32(1.0330222),
 np.float32(0.93963593),
 np.float32(0.99829847),
 np.float32(0.9301993),
 np.float32(0.9794725),
 np.float32(1.211552),
 np.float32(0.9918398)]

In [37]:
attack

[np.float32(1.0449789),
 np.float32(0.27989933),
 np.float32(1.2028192),
 np.float32(0.92873955),
 np.float32(2.8608744),
 np.float32(1.0118822),
 np.float32(0.20193313),
 np.float32(0.940445),
 np.float32(0.36129552),
 np.float32(1.5893075),
 np.float32(0.19574328),
 np.float32(0.12893632),
 np.float32(1.0634589),
 np.float32(3.2371392),
 np.float32(1.6274439),
 np.float32(1.0104213),
 np.float32(0.64610183),
 np.float32(0.9900791),
 np.float32(2.8332238),
 np.float32(2.7885067),
 np.float32(0.9573675),
 np.float32(1.2002716),
 np.float32(0.08911645),
 np.float32(1.1453863),
 np.float32(0.53330386),
 np.float32(1.0263541),
 np.float32(0.47848204),
 np.float32(6.070295),
 np.float32(1.9184173),
 np.float32(3.9990456),
 np.float32(0.93076366),
 np.float32(1.279311),
 np.float32(1.0205803),
 np.float32(0.20794706),
 np.float32(1.0453966),
 np.float32(1.4926038),
 np.float32(0.58408034),
 np.float32(2.1757438),
 np.float32(0.6339061),
 np.float32(5.2354565),
 np.float32(0.588946),
 np.float32(1.0843942),
 np.float32(0.11899645),
 np.float32(1.2162051),
 np.float32(2.2582715),
 np.float32(0.17206793),
 np.float32(0.6615488),
 np.float32(1.5794103),
 np.float32(2.603689),
 np.float32(1.0013636),
 np.float32(2.7393718),
 np.float32(0.9183021),
 np.float32(0.9827568),
 np.float32(0.27480975),
 np.float32(1.058123),
 np.float32(1.0336169),
 np.float32(0.86993533),
 np.float32(1.0138844),
 np.float32(1.0148216),
 np.float32(0.9449553),
 np.float32(3.021993),
 np.float32(1.2930645),
 np.float32(0.9214743),
 np.float32(4.925108),
 np.float32(1.1169997),
 np.float32(1.0373254),
 np.float32(0.9477199),
 np.float32(0.9759801),
 np.float32(1.5809051),
 np.float32(1.0692087),
 np.float32(1.0077904),
 np.float32(3.0885766),
 np.float32(0.5342935),
 np.float32(1.5677707),
 np.float32(1.7330855),
 np.float32(1.9234464),
 np.float32(0.9278758),
 np.float32(1.890119),
 np.float32(0.9711491),
 np.float32(4.705577),
 np.float32(0.25689882),
 np.float32(0.56239873),
 np.float32(0.9434778),
 np.float32(0.94325227),
 np.float32(0.9641718),
 np.float32(2.4842365),
 np.float32(2.3490303),
 np.float32(1.5908003),
 np.float32(0.5841615),
 np.float32(0.9764647),
 np.float32(0.92493),
 np.float32(2.9503279),
 np.float32(0.7618751),
 np.float32(1.0201498),
 np.float32(1.096289),
 np.float32(0.94931746),
 np.float32(0.740314),
 np.float32(1.0182211),
 np.float32(1.3825358),
 np.float32(0.9905663),
 np.float32(0.003367032),
 np.float32(1.8342314),
 np.float32(5.247325),
 np.float32(1.018463),
 np.float32(0.953049),
 np.float32(0.103668846),
 np.float32(2.0118334),
 np.float32(1.0521182),
 np.float32(2.103158),
 np.float32(2.0374963),
 np.float32(0.99958163),
 np.float32(4.5394554),
 np.float32(1.7055),
 np.float32(0.3817499),
 np.float32(0.96530485),
 np.float32(0.18871008),
 np.float32(2.8175814),
 np.float32(0.9237012),
 np.float32(0.59429455),
 np.float32(2.067437),
 np.float32(0.08758794),
 np.float32(1.5462807),
 np.float32(1.0494878),
 np.float32(1.6559201),
 np.float32(0.5075149),
 np.float32(1.0562408),
 np.float32(1.0619109),
 np.float32(1.537663),
 np.float32(1.0867321),
 np.float32(0.976564),
 np.float32(1.0677582),
 np.float32(0.78904724),
 np.float32(2.277965),
 np.float32(3.597625),
 np.float32(0.15851498),
 np.float32(0.73712546),
 np.float32(2.1411033),
 np.float32(1.1156805),
 np.float32(1.0333071),
 np.float32(2.2666428),
 np.float32(1.0733049),
 np.float32(2.8141606),
 np.float32(3.0276086),
 np.float32(2.1008754),
 np.float32(1.0063336),
 np.float32(3.4208658),
 np.float32(1.1215869),
 np.float32(3.0824373),
 np.float32(1.0037704),
 np.float32(1.079428),
 np.float32(1.0649154),
 np.float32(1.0380421),
 np.float32(1.0323234),
 np.float32(3.0385058),
 np.float32(1.0373313),
 np.float32(2.1176736),
 np.float32(1.095003),
 np.float32(0.94718796),
 np.float32(0.5464516),
 np.float32(0.72388256),
 np.float32(0.67494285),
 np.float32(0.4379183),
 np.float32(1.5000674),
 np.float32(1.2167403),
 np.float32(0.32752582),
 np.float32(0.8281825),
 np.float32(1.0162826),
 np.float32(0.24927126),
 np.float32(0.28358245),
 np.float32(1.932364),
 np.float32(0.95483315),
 np.float32(0.8184443),
 np.float32(1.0642953),
 np.float32(0.22536711),
 np.float32(1.7630597),
 np.float32(1.349267),
 np.float32(1.0482651),
 np.float32(1.1517655),
 np.float32(0.08367896),
 np.float32(0.2617385),
 np.float32(0.9582483),
 np.float32(0.9823471),
 np.float32(0.58765054),
 np.float32(0.4421789),
 np.float32(0.9308527),
 np.float32(0.93626076),
 np.float32(2.3063781),
 np.float32(1.0296298),
 np.float32(0.8715192),
 np.float32(0.9334375),
 np.float32(0.00435649),
 np.float32(1.3442268),
 np.float32(0.31091797),
 np.float32(2.6178424),
 np.float32(1.2322829),
 np.float32(0.50077826),
 np.float32(0.59414995),
 np.float32(0.28177467),
 np.float32(4.812515),
 np.float32(1.0168176),
 np.float32(2.2106383),
 np.float32(0.8032489),
 np.float32(1.7901114),
 np.float32(3.1477044),
 np.float32(0.97107345),
 np.float32(0.9670357),
 np.float32(1.0798899),
 np.float32(1.0270153),
 np.float32(1.0609064),
 np.float32(1.663248),
 np.float32(0.9607343),
 np.float32(4.1866717),
 np.float32(1.0059669),
 np.float32(0.9896137),
 np.float32(0.8258467),
 np.float32(1.0311413),
 np.float32(0.7870089),
 np.float32(0.94158965),
 np.float32(1.2500976),
 np.float32(2.02303),
 np.float32(1.0620627),
 np.float32(0.26592967),
 np.float32(3.0735083),
 np.float32(0.93265015),
 np.float32(1.2870822),
 np.float32(1.1652212),
 np.float32(2.5628688),
 np.float32(4.586723),
 np.float32(1.0039675),
 np.float32(0.59415823),
 np.float32(1.2969978),
 np.float32(0.99368584),
 np.float32(0.9960444),
 np.float32(1.7614118),
 np.float32(1.0568568),
 np.float32(1.01561),
 np.float32(1.160628),
 np.float32(1.9161078),
 np.float32(2.6248717),
 np.float32(1.0589222),
 np.float32(1.044071),
 np.float32(1.0146203),
 np.float32(0.94438004),
 np.float32(1.0931293),
 np.float32(1.1211566),
 np.float32(1.0575287),
 np.float32(0.8970112),
 np.float32(0.36420882),
 np.float32(0.45763892),
 np.float32(1.0381769),
 np.float32(0.8557491),
 np.float32(0.9542652),
 np.float32(0.43517658),
 np.float32(0.9952029),
 np.float32(1.7181159),
 np.float32(0.9082495),
 np.float32(2.9782326),
 np.float32(0.9676147),
 np.float32(0.9847233),
 np.float32(3.9967484),
 np.float32(1.4468884),
 np.float32(0.008138673),
 np.float32(1.0122578),
 np.float32(1.0941566),
 np.float32(1.0299107),
 np.float32(0.9567903),
 np.float32(0.49344516),
 np.float32(1.959262),
 np.float32(1.6618983),
 np.float32(0.3766549),
 np.float32(0.44677612),
 np.float32(1.0592055),
 np.float32(1.7621456),
 np.float32(3.2418194),
 np.float32(1.0641891),
 np.float32(0.3541991),
 np.float32(1.0479454),
 np.float32(4.8947806),
 np.float32(0.25194913),
 np.float32(0.6246018),
 np.float32(1.4664736),
 np.float32(0.9681484),
 np.float32(3.8136053),
 np.float32(5.553726),
 np.float32(1.916062),
 np.float32(0.97631735),
 np.float32(1.0578465),
 np.float32(0.76193124),
 np.float32(1.0106136),
 np.float32(0.22979505),
 np.float32(1.3100197),
 np.float32(1.4978287),
 np.float32(0.83385825),
 np.float32(0.6038661),
 np.float32(1.5566589),
 np.float32(1.0184819),
 np.float32(0.40578252),
 np.float32(0.88483113),
 np.float32(1.0894191),
 np.float32(1.0014099),
 np.float32(2.1975925),
 np.float32(3.7215006),
 np.float32(0.3547479),
 np.float32(0.079808876),
 np.float32(1.0160238),
 np.float32(0.9463473),
 np.float32(1.7588693),
 np.float32(3.3727162),
 np.float32(1.7647228),
 np.float32(0.9355168),
 np.float32(3.088063),
 np.float32(0.07552345),
 np.float32(1.9985263),
 np.float32(1.7773463),
 np.float32(0.37449858),
 np.float32(0.97722),
 np.float32(2.6932416),
 np.float32(0.8540368),
 np.float32(0.9861616),
 np.float32(2.4700546),
 np.float32(1.0045466),
 np.float32(0.936976),
 np.float32(0.8683675),
 np.float32(0.97622955),
 np.float32(3.16378),
 np.float32(0.9401668),
 np.float32(1.5251192),
 np.float32(0.99899256),
 np.float32(0.14017358),
 np.float32(0.9484817),
 np.float32(1.0264142),
 np.float32(1.0255314),
 np.float32(1.0704242),
 np.float32(1.0581062),
 np.float32(1.1049167),
 np.float32(0.97169566)]