In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
from src.dataLoader import getResultDataframe
from src.poissonModel import PoissonModel, poissonPdf
import polars as pl
import datetime
import numpy as np

In [3]:
df = getResultDataframe()
if df is None:
    df = pl.DataFrame()

In [4]:
df

shape: (49_477, 9)
┌────────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬─────────┐
│ date       ┆ home_team ┆ away_team ┆ home_scor ┆ … ┆ tournamen ┆ city      ┆ country   ┆ neutral │
│ ---        ┆ ---       ┆ ---       ┆ e         ┆   ┆ t         ┆ ---       ┆ ---       ┆ ---     │
│ str        ┆ str       ┆ str       ┆ ---       ┆   ┆ ---       ┆ str       ┆ str       ┆ bool    │
│            ┆           ┆           ┆ i64       ┆   ┆ str       ┆           ┆           ┆         │
╞════════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═════════╡
│ 1872-11-30 ┆ Scotland  ┆ England   ┆ 0         ┆ … ┆ Friendly  ┆ Glasgow   ┆ Scotland  ┆ false   │
│ 1873-03-08 ┆ England   ┆ Scotland  ┆ 4         ┆ … ┆ Friendly  ┆ London    ┆ England   ┆ false   │
│ 1874-03-07 ┆ Scotland  ┆ England   ┆ 2         ┆ … ┆ Friendly  ┆ Glasgow   ┆ Scotland  ┆ false   │
│ 1875-03-06 ┆ England   ┆ Scotland  ┆ 2         ┆ … ┆ Friendly  ┆ London    ┆ England   ┆ false   │
│ 1876-03-04 ┆ Scotland  ┆ England   ┆ 3         ┆ … ┆ Friendly  ┆ Glasgow   ┆ Scotland  ┆ false   │
│ …          ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …       │
│ 2026-06-27 ┆ Jordan    ┆ Argentina ┆ null      ┆ … ┆ FIFA      ┆ Arlington ┆ United    ┆ true    │
│            ┆           ┆           ┆           ┆   ┆ World Cup ┆           ┆ States    ┆         │
│ 2026-06-27 ┆ Colombia  ┆ Portugal  ┆ null      ┆ … ┆ FIFA      ┆ Miami     ┆ United    ┆ true    │
│            ┆           ┆           ┆           ┆   ┆ World Cup ┆ Gardens   ┆ States    ┆         │
│ 2026-06-27 ┆ DR Congo  ┆ Uzbekista ┆ null      ┆ … ┆ FIFA      ┆ Atlanta   ┆ United    ┆ true    │
│            ┆           ┆ n         ┆           ┆   ┆ World Cup ┆           ┆ States    ┆         │
│ 2026-06-27 ┆ Panama    ┆ England   ┆ null      ┆ … ┆ FIFA      ┆ East Ruth ┆ United    ┆ true    │
│            ┆           ┆           ┆           ┆   ┆ World Cup ┆ erford    ┆ States    ┆         │
│ 2026-06-27 ┆ Croatia   ┆ Ghana     ┆ null      ┆ … ┆ FIFA      ┆ Philadelp ┆ United    ┆ true    │
│            ┆           ┆           ┆           ┆   ┆ World Cup ┆ hia       ┆ States    ┆         │
└────────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴─────────┘

In [5]:
allTeams = list(set(df["home_team"].unique().to_list() + df["away_team"].unique().to_list()))
model = PoissonModel(teamList=allTeams)

In [6]:
stats = model.getTeamParamsDf()
stats

shape: (336, 3)
┌──────────────────┬─────────────────┬─────────────────┐
│ team             ┆ attackingParams ┆ defendingParams │
│ ---              ┆ ---             ┆ ---             │
│ str              ┆ f32             ┆ f32             │
╞══════════════════╪═════════════════╪═════════════════╡
│ Tibet            ┆ 0.972301        ┆ 1.017163        │
│ Panjab           ┆ 1.044684        ┆ 1.111448        │
│ Marshall Islands ┆ 1.149584        ┆ 1.05032         │
│ Mozambique       ┆ 1.002754        ┆ 1.018319        │
│ Benin            ┆ 1.011858        ┆ 0.969904        │
│ …                ┆ …               ┆ …               │
│ Gotland          ┆ 1.026222        ┆ 0.901369        │
│ Menorca          ┆ 1.039879        ┆ 0.976488        │
│ Australia        ┆ 1.027334        ┆ 0.99696         │
│ Lithuania        ┆ 0.997275        ┆ 1.052222        │
│ Artsakh          ┆ 1.05579         ┆ 0.990646        │
└──────────────────┴─────────────────┴─────────────────┘

In [7]:
model.getHomeMultiplier()

np.float32(0.95581186)

In [26]:
worldCupYear = 1998

In [27]:
scope = pl.lit(True)
scope = scope & (pl.col("date").is_between(datetime.date(worldCupYear-1, 6, 1), datetime.date(worldCupYear, 6, 1)))
scope = scope & (pl.all_horizontal([pl.col(column).is_not_null() for column in df.columns]))
model.fitPoisson(
    data=df,
    scopeExpr=scope,
    homeTeamExpr=pl.col("home_team"),
    awayTeamExpr=pl.col("away_team"),
    homeScoreExpr=pl.col("home_score"),
    awayScoreExpr=pl.col("away_score"),
    matchStatusExpr=pl.col("neutral"),
    numEpochs=10000
)

In [28]:
scopeTest = pl.lit(True)
scopeTest = scopeTest & (pl.col("tournament") == "FIFA World Cup")
scopeTest = scopeTest & (pl.col("date").is_between(datetime.date(worldCupYear, 1, 1), datetime.date(worldCupYear, 12, 31)))
dfTest = df.filter(scopeTest)

In [29]:
likelyhood = model.predictScore(
    dfTest,
    pl.col("home_team"),
    pl.col("away_team"),
    pl.col("home_score"),
    pl.col("away_score"),
    pl.when(~pl.col("neutral")).then(pl.col("home_team")).otherwise("neutral")
)

In [30]:
dfTest= dfTest.with_columns(likelyhood=likelyhood)

In [31]:
dfTest["likelyhood"].mean()

0.06951053169163102

In [ ]:
dfTest

shape: (64, 10)
┌────────────┬────────────┬────────────┬───────────┬───┬───────────┬─────────┬─────────┬───────────┐
│ date       ┆ home_team  ┆ away_team  ┆ home_scor ┆ … ┆ city      ┆ country ┆ neutral ┆ likelyhoo │
│ ---        ┆ ---        ┆ ---        ┆ e         ┆   ┆ ---       ┆ ---     ┆ ---     ┆ d         │
│ str        ┆ str        ┆ str        ┆ ---       ┆   ┆ str       ┆ str     ┆ bool    ┆ ---       │
│            ┆            ┆            ┆ i64       ┆   ┆           ┆         ┆         ┆ f64       │
╞════════════╪════════════╪════════════╪═══════════╪═══╪═══════════╪═════════╪═════════╪═══════════╡
│ 1998-06-10 ┆ Brazil     ┆ Scotland   ┆ 2         ┆ … ┆ Saint-Den ┆ France  ┆ true    ┆ 0.063426  │
│            ┆            ┆            ┆           ┆   ┆ is        ┆         ┆         ┆           │
│ 1998-06-10 ┆ Morocco    ┆ Norway     ┆ 2         ┆ … ┆ Montpelli ┆ France  ┆ true    ┆ 0.097104  │
│            ┆            ┆            ┆           ┆   ┆ er        ┆         ┆         ┆           │
│ 1998-06-11 ┆ Cameroon   ┆ Austria    ┆ 1         ┆ … ┆ Toulouse  ┆ France  ┆ true    ┆ 0.110124  │
│ 1998-06-11 ┆ Italy      ┆ Chile      ┆ 2         ┆ … ┆ Bordeaux  ┆ France  ┆ true    ┆ 0.054875  │
│ 1998-06-12 ┆ France     ┆ South      ┆ 3         ┆ … ┆ Marseille ┆ France  ┆ false   ┆ 0.047203  │
│            ┆            ┆ Africa     ┆           ┆   ┆           ┆         ┆         ┆           │
│ …          ┆ …          ┆ …          ┆ …         ┆ … ┆ …         ┆ …       ┆ …       ┆ …         │
│ 1998-07-04 ┆ Netherland ┆ Argentina  ┆ 2         ┆ … ┆ Marseille ┆ France  ┆ true    ┆ 0.094871  │
│            ┆ s          ┆            ┆           ┆   ┆           ┆         ┆         ┆           │
│ 1998-07-07 ┆ Brazil     ┆ Netherland ┆ 1         ┆ … ┆ Marseille ┆ France  ┆ true    ┆ 0.053212  │
│            ┆            ┆ s          ┆           ┆   ┆           ┆         ┆         ┆           │
│ 1998-07-08 ┆ France     ┆ Croatia    ┆ 2         ┆ … ┆ Saint-Den ┆ France  ┆ false   ┆ 0.046065  │
│            ┆            ┆            ┆           ┆   ┆ is        ┆         ┆         ┆           │
│ 1998-07-11 ┆ Netherland ┆ Croatia    ┆ 1         ┆ … ┆ Paris     ┆ France  ┆ true    ┆ 0.011142  │
│            ┆ s          ┆            ┆           ┆   ┆           ┆         ┆         ┆           │
│ 1998-07-12 ┆ France     ┆ Brazil     ┆ 3         ┆ … ┆ Saint-Den ┆ France  ┆ false   ┆ 0.133451  │
│            ┆            ┆            ┆           ┆   ┆ is        ┆         ┆         ┆           │
└────────────┴────────────┴────────────┴───────────┴───┴───────────┴─────────┴─────────┴───────────┘

In [15]:
model.getTeamParamsDf().filter(pl.col("team")=="France")

shape: (1, 3)
┌────────┬─────────────────┬─────────────────┐
│ team   ┆ attackingParams ┆ defendingParams │
│ ---    ┆ ---             ┆ ---             │
│ str    ┆ f32             ┆ f32             │
╞════════╪═════════════════╪═════════════════╡
│ France ┆ 3.800171        ┆ 3.904303        │
└────────┴─────────────────┴─────────────────┘

In [16]:
model.getTeamParamsDf().filter(pl.col("team")=="Germany")

shape: (1, 3)
┌─────────┬─────────────────┬─────────────────┐
│ team    ┆ attackingParams ┆ defendingParams │
│ ---     ┆ ---             ┆ ---             │
│ str     ┆ f32             ┆ f32             │
╞═════════╪═════════════════╪═════════════════╡
│ Germany ┆ 4.339887        ┆ 2.399774        │
└─────────┴─────────────────┴─────────────────┘

In [18]:
dfTest

shape: (64, 10)
┌────────────┬────────────┬────────────┬───────────┬───┬───────────┬─────────┬─────────┬───────────┐
│ date       ┆ home_team  ┆ away_team  ┆ home_scor ┆ … ┆ city      ┆ country ┆ neutral ┆ likelyhoo │
│ ---        ┆ ---        ┆ ---        ┆ e         ┆   ┆ ---       ┆ ---     ┆ ---     ┆ d         │
│ str        ┆ str        ┆ str        ┆ ---       ┆   ┆ str       ┆ str     ┆ bool    ┆ ---       │
│            ┆            ┆            ┆ i64       ┆   ┆           ┆         ┆         ┆ f64       │
╞════════════╪════════════╪════════════╪═══════════╪═══╪═══════════╪═════════╪═════════╪═══════════╡
│ 2014-06-12 ┆ Brazil     ┆ Croatia    ┆ 3         ┆ … ┆ São Paulo ┆ Brazil  ┆ false   ┆ 0.07603   │
│ 2014-06-13 ┆ Chile      ┆ Australia  ┆ 3         ┆ … ┆ Cuiabá    ┆ Brazil  ┆ true    ┆ 0.036976  │
│ 2014-06-13 ┆ Mexico     ┆ Cameroon   ┆ 1         ┆ … ┆ Natal     ┆ Brazil  ┆ true    ┆ 0.05124   │
│ 2014-06-13 ┆ Spain      ┆ Netherland ┆ 1         ┆ … ┆ Salvador  ┆ Brazil  ┆ true    ┆ 0.115301  │
│            ┆            ┆ s          ┆           ┆   ┆           ┆         ┆         ┆           │
│ 2014-06-14 ┆ Colombia   ┆ Greece     ┆ 3         ┆ … ┆ Belo      ┆ Brazil  ┆ true    ┆ 0.084572  │
│            ┆            ┆            ┆           ┆   ┆ Horizonte ┆         ┆         ┆           │
│ …          ┆ …          ┆ …          ┆ …         ┆ … ┆ …         ┆ …       ┆ …       ┆ …         │
│ 2014-07-05 ┆ Netherland ┆ Costa Rica ┆ 0         ┆ … ┆ Salvador  ┆ Brazil  ┆ true    ┆ 0.017397  │
│            ┆ s          ┆            ┆           ┆   ┆           ┆         ┆         ┆           │
│ 2014-07-08 ┆ Brazil     ┆ Germany    ┆ 1         ┆ … ┆ Belo      ┆ Brazil  ┆ false   ┆ 0.063035  │
│            ┆            ┆            ┆           ┆   ┆ Horizonte ┆         ┆         ┆           │
│ 2014-07-09 ┆ Netherland ┆ Argentina  ┆ 0         ┆ … ┆ São Paulo ┆ Brazil  ┆ true    ┆ 0.17744   │
│            ┆ s          ┆            ┆           ┆   ┆           ┆         ┆         ┆           │
│ 2014-07-12 ┆ Brazil     ┆ Netherland ┆ 0         ┆ … ┆ Brasília  ┆ Brazil  ┆ false   ┆ 0.120366  │
│            ┆            ┆ s          ┆           ┆   ┆           ┆         ┆         ┆           │
│ 2014-07-13 ┆ Germany    ┆ Argentina  ┆ 1         ┆ … ┆ Rio de    ┆ Brazil  ┆ true    ┆ 0.042114  │
│            ┆            ┆            ┆           ┆   ┆ Janeiro   ┆         ┆         ┆           │
└────────────┴────────────┴────────────┴───────────┴───┴───────────┴─────────┴─────────┴───────────┘